### ISSUE TITLE
issue 2

### ISSUE THREAD

**Issue by pjka** [ofeksadlo/lichess-cheat#2]
thank you sir,
but one lit problem facing
Traceback (most recent call last):
File "C:\Users\monty\Desktop\lichess-cheat-master\main.py", line 5, in
from stockfish import Stockfish
ModuleNotFoundError: No module named 'stockfish'

it shows even if i've installed stockfish

**Comment by ofeksadlo** [comment]
You need to install the stockfish wraper [https://pypi.org/project/stockfish/](https://pypi.org/project/stockfish/)

My bad I'll add it to the readme

**Comment by ofeksadlo** [comment]
Added requirements in the readme check it out
