### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by pjka** [ofeksadlo/lichess-cheat#3]
![Screenshot (24)](https://user-images.githubusercontent.com/70917452/94332374-55826980-fff2-11ea-994b-d89582b00f2d.png)
board not open only showing this on left corner

**Comment by ofeksadlo** [comment]
Have you configured in the config.ini your starting color?

**Comment by pjka** [comment]
error after error , after solving one error , another error occurs, my humble request that please make youtube video how to start this porgram step by step....

**Comment by ofeksadlo** [comment]
Your exception indicated it cannot find the engine exe file. Most
likely because it's on another drive than the python script running on.

To solve try putting the engine exe file on the same drive as the python script running on.
