### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by interlo0p** [ofeksadlo/lichess-cheat#8]
https://ibb.co/Cw34CY0

**Comment by ofeksadlo** [comment]
Quite difficult to tell.
But my guess is you are clicking outside of board when the program
is trying to get the "from cell" using mouse clicked position.
If you click outside of the board then this exception should appear.

So follow this guidelines:
1) Open up a game while logged in to lichess (Playing as anonymous will change the board size and mess everything
    Also it's only tested on chrome and on 100% zoom while logged in).
2) During the freeze time open up the program choose your starting color. And alt+tab back to the browser (Don't use your 
    mouse).
    Keep in mind that your mouse clicks from that moment matters. So play like that: 1 click from cell and 1 click to cell
    when it's your turn.
    No dragging pieces.
    No checking youtube for a second
    It will mess everything and the program will crash.

This project is far from being done. But still works like charm when you get the hang of it.

Keep in mind that lichess would most definitely ban you for using this against real players.
So I suggest you to test against bots to learn in the process.

Let me know if you're having anymore issue.
